# Generated by Django 5.1.3 on 2024-12-26 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('media_type', models.CharField(choices=[('serie', 'Serie'), ('film', 'Film')], max_length=10)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('synopsis', models.CharField(max_length=512)),
                ('actors', models.ManyToManyField(blank=True, related_name='media_actor', to='brMedia.actor')),
                ('directors', models.ManyToManyField(blank=True, related_name='media_director', to='brMedia.director')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=512, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255, unique=True)),
                ('password', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('media_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='brMedia.media')),
                ('duration', models.CharField(blank=True, max_length=255, null=True)),
            ],
            bases=('brMedia.media',),
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('media_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='brMedia.media')),
                ('seasons', models.IntegerField(blank=True, null=True)),
                ('episodes', models.IntegerField(blank=True, null=True)),
            ],
            bases=('brMedia.media',),
        ),
        migrations.AddField(
            model_name='media',
            name='genre',
            field=models.ManyToManyField(blank=True, related_name='media_genre', to='brMedia.genre'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rev_date', models.DateField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=512, null=True)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brMedia.media')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brMedia.person')),
            ],
        ),
        migrations.CreateModel(
            name='Visualization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_date', models.DateField(blank=True, null=True)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brMedia.media')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brMedia.person')),
            ],
        ),
    ]
